### ISSUE TITLE
error when running the command on the server side

### ISSUE THREAD

**Issue by LingEmberMaple** [FlyingShuriken/MCDR-plugins#1]
```
> !!rsc
[Server] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [Server thread/INFO]: !!rsc<--[HERE]
> !!rsclist
[Server] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [Server thread/INFO]: !!rsclist<--[HERE]
[Server] [Server thread/INFO]: <LingEmberMaple> !!rsc
> !!rsc
[Server] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [Server thread/INFO]: !!rsc<--[HERE]
> !!rsclist
[Server] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [Server thread/INFO]: !!rsclist<--[HERE]
> !!rscadd op 3
[MCDR] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=run_some_commands@1.0.0,priority=1000,callback=<function on_user_info at 0x00000212C0425B20>]
Traceback (most recent call last):
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\run_some_commands_v1.0.0.mcdr\run_some_commands\__init__.py", line 41, in on_user_info
    if server.get_permission_level(info.player) == 4:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\server_interface.py", line 820, in get_permission_level
    raise TypeError('Unsupported permission level querying for type {}'.format(type(obj)))
TypeError: Unsupported permission level querying for type <class 'NoneType'>
[Server] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [Server thread/INFO]: !!rscadd op 3<--[HERE]
> !!rsc op
[MCDR] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=run_some_commands@1.0.0,priority=1000,callback=<function on_user_info at 0x00000212C0425B20>]
Traceback (most recent call last):
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\run_some_commands_v1.0.0.mcdr\run_some_commands\__init__.py", line 63, in on_user_info
    prm_lvl = server.get_permission_level(info.player)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\server_interface.py", line 820, in get_permission_level
    raise TypeError('Unsupported permission level querying for type {}'.format(type(obj)))
TypeError: Unsupported permission level querying for type <class 'NoneType'>
[Server] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [Server thread/INFO]: !!rsc op<--[HERE]
> !!rscrem op
[MCDR] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=run_some_commands@1.0.0,priority=1000,callback=<function on_user_info at 0x00000212C0425B20>]
Traceback (most recent call last):
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\run_some_commands_v1.0.0.mcdr\run_some_commands\__init__.py", line 52, in on_user_info
    if server.get_permission_level(info.player) == 4:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Applications\Python312\Lib\site-packages\mcdreforged\plugin\server_interface.py", line 820, in get_permission_level
    raise TypeError('Unsupported permission level querying for type {}'.format(type(obj)))
TypeError: Unsupported permission level querying for type <class 'NoneType'>
[Server] [Server thread/INFO]: Unknown or incomplete command, see below for error
[Server] [Server thread/INFO]: !!rscrem op<--[HERE]
```

**Comment by LingEmberMaple** [comment]
It should at least support running "!! rsclist", "!! rscadd" and "!! rscrem" on the server side?

**Comment by FlyingShuriken** [comment]
> It should at least support running "!! rsclist", "!! rscadd" and "!! rscrem" on the server side?

Hey! Thanks for using my plugin.
I did not touch MC and this plugin for quite some time, so I'm not sure if this plugin still works(although it should).
Not very sure whether the feature you mentioned was do-able at the time I created this plugin.
Perhaps you can try to re-create the feature you mentioned by creating a PR, or I will try to work on it while I am free.
Thanks!
